# Generated by Django 2.0.5 on 2018-05-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('upload_time', models.DateTimeField(auto_now=True, verbose_name='文件夹修改日期')),
                ('privacy', models.BooleanField(default=True, verbose_name='私密性')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '回收站'), (3, '彻底删除')], default=1, verbose_name='文件夹状态')),
            ],
            options={
                'verbose_name': '文件夹',
                'verbose_name_plural': '文件夹',
            },
        ),
    ]
