# Generated by Django 2.0.5 on 2018-06-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0005_auto_20180605_0942'),
    ]

    operations = [

    ]
