# Generated by Django 2.0.5 on 2018-06-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0006_remove_folder_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='privacy',
        ),
    ]
