# Generated by Django 2.0.5 on 2018-05-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='相册描述')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('upload_time', models.DateTimeField(auto_now=True, verbose_name='相册修改日期')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '回收站'), (3, '彻底删除')], default=1, verbose_name='相册状态')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
            },
        ),
        migrations.CreateModel(
            name='AlbumMemberShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_time', models.DateTimeField(auto_now_add=True, verbose_name='相册成员邀请日期')),
            ],
            options={
                'verbose_name': '相册-用户关系表',
                'verbose_name_plural': '相册-用户关系表',
            },
        ),
        migrations.CreateModel(
            name='AlbumPhotoShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='相册照片添加日期')),
            ],
            options={
                'verbose_name': '相册-照片关系表',
                'verbose_name_plural': '相册-照片关系表',
            },
        ),
    ]
