# Generated by Django 2.0.5 on 2018-05-22 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0001_initial'),
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumphotoship',
            name='adder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albumphotoship_adder', to=settings.AUTH_USER_MODEL, verbose_name='相册照片添加者'),
        ),
        migrations.AddField(
            model_name='albumphotoship',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumphotoship_album', to='album.Album', verbose_name='相册'),
        ),
        migrations.AddField(
            model_name='albumphotoship',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumphotoship_photo', to='photo.Photo', verbose_name='相册照片'),
        ),
        migrations.AddField(
            model_name='albummembership',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albummembership_album', to='album.Album', verbose_name='相册'),
        ),
        migrations.AddField(
            model_name='albummembership',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albummembership_invites', to=settings.AUTH_USER_MODEL, verbose_name='相册成员邀请者'),
        ),
        migrations.AddField(
            model_name='albummembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albummembership_member', to=settings.AUTH_USER_MODEL, verbose_name='相册成员'),
        ),
        migrations.AddField(
            model_name='album',
            name='members',
            field=models.ManyToManyField(through='album.AlbumMemberShip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(through='album.AlbumPhotoShip', to='photo.Photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterUniqueTogether(
            name='albumphotoship',
            unique_together={('album', 'photo')},
        ),
        migrations.AlterUniqueTogether(
            name='albummembership',
            unique_together={('album', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('user', 'name')},
        ),
    ]
