# Generated by Django 2.0.5 on 2018-06-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20180522_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('Normal', '正常'), ('Recycler', '回收站'), ('Deleted', '彻底删除')], default='Normal', max_length=10, verbose_name='相册状态'),
        ),
    ]
