# Generated by Django 2.0.5 on 2018-06-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180605_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cloud',
        ),
    ]
