# Generated by Django 2.0.5 on 2018-06-18 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0011_merge_20180618_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.CharField(max_length=100, unique=True, verbose_name='脸的标识')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_user', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '人脸',
                'verbose_name_plural': '人脸',
            },
        ),
        migrations.CreateModel(
            name='FaceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facefile_face', to='face.Face', verbose_name='脸')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facefile_photo', to='photo.Photo', verbose_name='照片')),
            ],
            options={
                'verbose_name': '人脸文件',
                'verbose_name_plural': '人脸文件',
            },
        ),
    ]
