# Generated by Django 2.0.5 on 2018-05-22 05:12

from django.db import migrations, models
import django.db.models.deletion
import photo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('upload_time', models.DateTimeField(auto_now=True, verbose_name='照片上传日期')),
                ('upload_place', models.CharField(blank=True, default='Default Place', max_length=20, null=True)),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '回收站'), (3, '彻底删除')], default=1, verbose_name='照片状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='照片描述')),
                ('selected_times', models.IntegerField(blank=True, default=0, null=True, verbose_name='照片选择次数')),
                ('is_scenic', models.BooleanField(default=False, verbose_name='风景')),
                ('is_character', models.BooleanField(default=False, verbose_name='人物')),
                ('is_book', models.BooleanField(default=False, verbose_name='书本')),
                ('is_cartoon', models.BooleanField(default=False, verbose_name='动漫')),
                ('privacy', models.BooleanField(default=True, verbose_name='私密的')),
                ('file', models.FileField(upload_to=photo.models.photo_storage_path, verbose_name='照片路径')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_folder', to='folder.Folder', verbose_name='所属文件夹')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
            },
        ),
    ]
