# Generated by Django 2.0.5 on 2018-06-16 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20180616_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '照片实体关系',
                'verbose_name_plural': '照片实体关系',
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.AlterField(
            model_name='entity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_category', to='photo.Category', verbose_name='种类'),
        ),
        migrations.AddField(
            model_name='photoentity',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photoentity_entity', to='photo.Entity', verbose_name='实体'),
        ),
        migrations.AddField(
            model_name='photoentity',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photoentity_photo', to='photo.Photo', verbose_name='照片'),
        ),
    ]
