# Generated by Django 2.0.5 on 2018-06-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20180616_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='privacy',
        ),
    ]
