# Generated by Django 2.0.5 on 2018-06-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_remove_photo_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=10, unique=True, verbose_name='种类'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity',
            field=models.CharField(max_length=10, unique=True, verbose_name='实体'),
        ),
    ]
