# Generated by Django 2.0.5 on 2018-06-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20180616_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity',
            field=models.CharField(max_length=20, unique=True, verbose_name='实体'),
        ),
    ]
