# Generated by Django 2.0.5 on 2018-06-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20180616_0919'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photoentity',
            unique_together={('entity', 'photo')},
        ),
    ]
