# Generated by Django 2.0.5 on 2018-06-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_auto_20180616_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Android路径'),
        ),
    ]
