# Generated by Django 2.0.5 on 2018-06-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20180605_0942'),
        ('photo', '0010_photo_path'),
    ]

    operations = [
    ]
